"""为 Message 添加 is_complete 列

Revision ID: 4fd2b8cde52e
Revises: 141d701ef347
Create Date: 2026-08-12 22:03:06.979535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd2b8cde52e'
down_revision: Union[str, Sequence[str], None] = '141d701ef347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'messages', 
        sa.Column(
            'is_complete',
            sa.Boolean(), 
            nullable=False,
            server_default=sa.true()
        )
    )

    # server_default 只用于回填历史消息；之后强制所有新写入显式声明完整性。
    op.alter_column(
        "messages",
        "is_complete",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_complete')
    # ### end Alembic commands ###
